### ISSUE TITLE
Assembler permanently crashes with SEGFAULT, all tests fail

### ISSUE THREAD

**Issue by vladikcomper** [Clownacy/clownassembler#4]
There's a serious bug in Clownassembler, where any output causes it to crash with SEGFAULT. This includes built-in tests. Literally every test fails on my system:

```
0% tests passed, 16 tests failed out of 16

Total Test time (real) =   1.18 sec

The following tests FAILED:
          1 - misc (SEGFAULT)
          2 - INSTURCTION_MOVE_TO_SR_VALID (SEGFAULT)
          3 - INSTURCTION_MOVE_TO_SR_INVALID_1 (SEGFAULT)
          4 - INSTURCTION_MOVE_TO_SR_INVALID_2 (SEGFAULT)
          5 - INSTURCTION_MOVE_TO_SR_INVALID_3 (SEGFAULT)
          6 - INSTURCTION_MOVE_TO_SR_INVALID_4 (SEGFAULT)
          7 - INSTURCTION_MOVE_TO_SR_INVALID_5 (SEGFAULT)
          8 - valid_instructions_assemble (SEGFAULT)
          9 - valid_instructions_compare (Failed)
         10 - sonic_1_assemble (Failed)
         11 - sonic_1_compare (Failed)
         12 - 68_katy_basic_assemble (SEGFAULT)
         13 - 68_katy_basic_compare (Failed)
         14 - sonic_spinball_assemble (Failed)
         15 - sonic_2_august_21st_assemble (Failed)
         16 - sonic_2_august_21st_compare (Failed)
```

Quick investigation shows that it's caused by `fputc` call with `NULL` instead of a proper stream.

For instance, assembling a simple "RTS" instruction crashes with the following backtrace:
```
(gdb) bt
#0  0x00007ffff7e3872d in fputc (c=32, fp=0x0) at ./libio/fputc.c:35
#1  0x0000555555559e87 in OutputByte (state=state@entry=0x7fffffffd660, byte=byte@entry=78) at semantic.c:369
#2  0x000055555555c9a1 in ProcessInstruction (state=state@entry=0x7fffffffd660, instruction=instruction@entry=0x7fffffffd468) at semantic.c:3629
#3  0x000055555555d164 in ProcessStatement (state=state@entry=0x7fffffffd660, statement=statement@entry=0x7fffffffd460, label=label@entry=0x0) at semantic.c:4100
#4  0x000055555555d6fa in ParseLine (state=state@entry=0x7fffffffd660, source_line=source_line@entry=0x7fffffffd6c8 " rts", label=label@entry=0x0, 
    directive_and_operands=directive_and_operands@entry=0x7fffffffd6c9 "rts") at semantic.c:4413
#5  0x000055555555db87 in AssembleLine (state=state@entry=0x7fffffffd660, source_line=source_line@entry=0x7fffffffd6c8 " rts") at semantic.c:4652
#6  0x000055555555e3c6 in AssembleFile (state=state@entry=0x7fffffffd660, input_file=input_file@entry=0x55555556e2a0) at semantic.c:5092
#7  0x000055555555e6d4 in ClownAssembler_Assemble (input_file=input_file@entry=0x55555556e2a0, output_file=output_file@entry=0x55555556e480, listing_file=listing_file@entry=0x0, 
    symbol_file=symbol_file@entry=0x0, input_file_path=input_file_path@entry=0x7fffffffe0d6 "test.asm", debug=<optimized out>, case_insensitive=0 '\000', equ_set_descope_local_labels=0 '\000')
    at semantic.c:5236
#8  0x000055555555750d in main (argc=<optimized out>, argv=0x7fffffffdcf8) at frontend_custom.c:189
```

This is the faulty code in question and it's related to rendering byte in a listing file:

https://github.com/Clownacy/clownassembler/blob/d0cc48241a33018f23df02ec82df6739432d4c85/semantic.c#L368-L371

It's clearly missing `state->listing_file != NULL` check, so it attempts to write even if the file is `NULL`.

When explicitly setting a listing file path in assembler options, it works as expected.

**Comment by Clownacy** [comment]
Thanks for finding this.

**Comment by vladikcomper** [comment]
Wow, that was fast! :)
